import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Uploader from '../components/Uploader'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>File Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Uploader />
      </main>
    </div>
  )
}
